version: "3"

volumes:
  db:
  
services:
  database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    expose:
      - 27017
      
  backend:
    image: sreevidya1237/ontologybe:123
    container_name: ontology-be
    ports:
      - 8080:8080
    links:
      - database

  frontend:
    image: sreevidya1237/ontologyfe:123
    container_name: ontology-fe
    ports:
      - 3000:3000
    links:
      - backend

  
    

  

